/* tslint:disable */
/* eslint-disable */
/**
 * Genius Yield Sumsub Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ApplicantId
 */
export interface ApplicantId {
    /**
     * 
     * @type {string}
     * @memberof ApplicantId
     */
    'id': string;
}
/**
 * 
 * @export
 * @interface SumsubAccessToken
 */
export interface SumsubAccessToken {
    /**
     * 
     * @type {string}
     * @memberof SumsubAccessToken
     */
    'token': string;
}
/**
 * 
 * @export
 * @interface SumsubApplicant
 */
export interface SumsubApplicant {
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicant
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicant
     */
    'createDate': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicant
     */
    'reviewDate': string;
    /**
     * 
     * @type {SumsubApplicantInfo}
     * @memberof SumsubApplicant
     */
    'info': SumsubApplicantInfo;
    /**
     * 
     * @type {SumsubReviewResult}
     * @memberof SumsubApplicant
     */
    'reviewStatus'?: SumsubReviewResult;
}
/**
 * 
 * @export
 * @interface SumsubApplicantAllOf
 */
export interface SumsubApplicantAllOf {
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantAllOf
     */
    'createDate': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantAllOf
     */
    'reviewDate': string;
    /**
     * 
     * @type {SumsubApplicantInfo}
     * @memberof SumsubApplicantAllOf
     */
    'info': SumsubApplicantInfo;
    /**
     * 
     * @type {SumsubReviewResult}
     * @memberof SumsubApplicantAllOf
     */
    'reviewStatus'?: SumsubReviewResult;
}
/**
 * 
 * @export
 * @interface SumsubApplicantInfo
 */
export interface SumsubApplicantInfo {
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantInfo
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantInfo
     */
    'nationality': string;
    /**
     * 
     * @type {Array<SumsubIdentityDocument>}
     * @memberof SumsubApplicantInfo
     */
    'idDocs'?: Array<SumsubIdentityDocument>;
}
/**
 * 
 * @export
 * @interface SumsubApplicantReference
 */
export interface SumsubApplicantReference {
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantReference
     */
    'applicantId': string;
}
/**
 * 
 * @export
 * @interface SumsubApplicantStatus
 */
export interface SumsubApplicantStatus {
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatus
     */
    'applicantId': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatus
     */
    'levelName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatus
     */
    'createDate': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatus
     */
    'reviewDate': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatus
     */
    'reviewStatus': string;
    /**
     * 
     * @type {SumsubReviewResult}
     * @memberof SumsubApplicantStatus
     */
    'reviewResult'?: SumsubReviewResult;
}
/**
 * 
 * @export
 * @interface SumsubApplicantStatusAllOf
 */
export interface SumsubApplicantStatusAllOf {
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatusAllOf
     */
    'levelName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatusAllOf
     */
    'createDate': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatusAllOf
     */
    'reviewDate': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubApplicantStatusAllOf
     */
    'reviewStatus': string;
    /**
     * 
     * @type {SumsubReviewResult}
     * @memberof SumsubApplicantStatusAllOf
     */
    'reviewResult'?: SumsubReviewResult;
}
/**
 * 
 * @export
 * @interface SumsubCreateApplicant
 */
export interface SumsubCreateApplicant {
    /**
     * 
     * @type {string}
     * @memberof SumsubCreateApplicant
     */
    'sourceKey': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubCreateApplicant
     */
    'externalUserId': string;
}
/**
 * 
 * @export
 * @interface SumsubIdentityDocument
 */
export interface SumsubIdentityDocument {
    /**
     * 
     * @type {string}
     * @memberof SumsubIdentityDocument
     */
    'idDocType': string;
    /**
     * 
     * @type {string}
     * @memberof SumsubIdentityDocument
     */
    'validUntil': string;
}
/**
 * 
 * @export
 * @interface SumsubReviewResult
 */
export interface SumsubReviewResult {
    /**
     * 
     * @type {string}
     * @memberof SumsubReviewResult
     */
    'reviewAnswer': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} userId ID of an user
         * @param {string} levelName access token level name
         * @param {number} ttlInSecs access token time to live in seconds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAccessToken: async (userId: string, levelName: string, ttlInSecs: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('createAccessToken', 'userId', userId)
            // verify required parameter 'levelName' is not null or undefined
            assertParamExists('createAccessToken', 'levelName', levelName)
            // verify required parameter 'ttlInSecs' is not null or undefined
            assertParamExists('createAccessToken', 'ttlInSecs', ttlInSecs)
            const localVarPath = `/resources/accessTokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (levelName !== undefined) {
                localVarQueryParameter['levelName'] = levelName;
            }

            if (ttlInSecs !== undefined) {
                localVarQueryParameter['ttlInSecs'] = ttlInSecs;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} levelName access token level name
         * @param {SumsubCreateApplicant} [sumsubCreateApplicant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createApplicant: async (levelName: string, sumsubCreateApplicant?: SumsubCreateApplicant, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'levelName' is not null or undefined
            assertParamExists('createApplicant', 'levelName', levelName)
            const localVarPath = `/resources/applicants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (levelName !== undefined) {
                localVarQueryParameter['levelName'] = levelName;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sumsubCreateApplicant, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<string>} applicantId ID of an applicant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicant: async (applicantId: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'applicantId' is not null or undefined
            assertParamExists('getApplicant', 'applicantId', applicantId)
            const localVarPath = `/resources/applicants/${applicantId}/one`
                .replace(`{${"applicantId"}}`, encodeURIComponent(String(applicantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} userId ID of an user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicantByUserId: async (userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getApplicantByUserId', 'userId', userId)
            const localVarPath = `/resources/applicants/-;externalUserId=${userId}/one`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<string>} applicantId ID of an applicant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicantStatus: async (applicantId: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'applicantId' is not null or undefined
            assertParamExists('getApplicantStatus', 'applicantId', applicantId)
            const localVarPath = `/resources/applicants/${applicantId}/status`
                .replace(`{${"applicantId"}}`, encodeURIComponent(String(applicantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} userId ID of an user
         * @param {string} levelName access token level name
         * @param {number} ttlInSecs access token time to live in seconds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAccessToken(userId: string, levelName: string, ttlInSecs: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SumsubAccessToken>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAccessToken(userId, levelName, ttlInSecs, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} levelName access token level name
         * @param {SumsubCreateApplicant} [sumsubCreateApplicant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createApplicant(levelName: string, sumsubCreateApplicant?: SumsubCreateApplicant, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SumsubApplicant>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createApplicant(levelName, sumsubCreateApplicant, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {Array<string>} applicantId ID of an applicant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApplicant(applicantId: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SumsubApplicant>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApplicant(applicantId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} userId ID of an user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApplicantByUserId(userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SumsubApplicant>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApplicantByUserId(userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {Array<string>} applicantId ID of an applicant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApplicantStatus(applicantId: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SumsubApplicantStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApplicantStatus(applicantId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {string} userId ID of an user
         * @param {string} levelName access token level name
         * @param {number} ttlInSecs access token time to live in seconds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAccessToken(userId: string, levelName: string, ttlInSecs: number, options?: any): AxiosPromise<SumsubAccessToken> {
            return localVarFp.createAccessToken(userId, levelName, ttlInSecs, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} levelName access token level name
         * @param {SumsubCreateApplicant} [sumsubCreateApplicant] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createApplicant(levelName: string, sumsubCreateApplicant?: SumsubCreateApplicant, options?: any): AxiosPromise<SumsubApplicant> {
            return localVarFp.createApplicant(levelName, sumsubCreateApplicant, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Array<string>} applicantId ID of an applicant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicant(applicantId: Array<string>, options?: any): AxiosPromise<SumsubApplicant> {
            return localVarFp.getApplicant(applicantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} userId ID of an user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicantByUserId(userId: string, options?: any): AxiosPromise<SumsubApplicant> {
            return localVarFp.getApplicantByUserId(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Array<string>} applicantId ID of an applicant
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicantStatus(applicantId: Array<string>, options?: any): AxiosPromise<SumsubApplicantStatus> {
            return localVarFp.getApplicantStatus(applicantId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {string} userId ID of an user
     * @param {string} levelName access token level name
     * @param {number} ttlInSecs access token time to live in seconds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createAccessToken(userId: string, levelName: string, ttlInSecs: number, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createAccessToken(userId, levelName, ttlInSecs, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} levelName access token level name
     * @param {SumsubCreateApplicant} [sumsubCreateApplicant] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createApplicant(levelName: string, sumsubCreateApplicant?: SumsubCreateApplicant, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createApplicant(levelName, sumsubCreateApplicant, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Array<string>} applicantId ID of an applicant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getApplicant(applicantId: Array<string>, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getApplicant(applicantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} userId ID of an user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getApplicantByUserId(userId: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getApplicantByUserId(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Array<string>} applicantId ID of an applicant
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getApplicantStatus(applicantId: Array<string>, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getApplicantStatus(applicantId, options).then((request) => request(this.axios, this.basePath));
    }
}


