export const LOCAL_STORAGE_KEYS = {
  USER_CONNECTED_WALLET_TYPE: 'USER_CONNECTED_WALLET_TYPE',
  RESTRICTED_USER_BANNER_DISMISSED: 'RESTRICTED_USER_BANNER_DISMISSED',
  TERMS_OF_USE_BANNER_DISMISSED: 'TERMS_OF_USE_BANNER_DISMISSED',
  STAKING_V2_LAUNCH_DIALOG_DISMISSED: 'STAKING_V2_LAUNCH_DIALOG_DISMISSED',
  SELECTED_MARKET_DATA_CHART_TYPE: 'SELECTED_MARKET_DATA_CHART_TYPE',
};
