#!/usr/bin/env bash

# check readme for more info about this file https://github.com/geniusyield/dex-api-server/blob/main/src/implementation/fastify/schemas/readme.MD

schema() {
  dir="$1"
  model="$2"
  mkdir -pv "src/implementation/fastify/schemas/${dir}"
  yarn typescript-json-schema ./tsconfig.build.json "${model}" \
    --include "src/types.ts" \
    --include "src/domain/models/${dir}/**.ts" \
    --refs false \
    --required true \
    --constAsEnum true \
    -o "src/implementation/fastify/schemas/${dir}/${model}Schema.json"
}

### Dex / Launchpad :: General
schema "private" "AssetPairReference"
schema "public" "CirculatingSupply"

### Dex / Launchpad :: On-Chain Event
# Currently cannot be used due to recursive type `PlutusDataField` which cannot
# be generated by `typescript-json-schema`
# schema "oura" "Event"

## Dex / Launchpad :: Transaction
schema "public" "OrderReference"
schema "public" "SignedTransaction"
schema "public" "TransactionSubmitSuccessResponse"
schema "public" "TransactionSubmitAcceptedResponse"
schema "public" "UnsignedTransaction"

### Launchpad :: User
schema "private" "KycSumsubEvent"
schema "public" "TermsAccept"
schema "public" "UserConnect"
schema "public" "UserConnectResponse"
schema "public" "WalletAccount"

### DEX :: Order Book
schema "public" "OrderBook"

### Launchpad :: Order Sale
schema "private" "OrderSalePortfolioQuery"
schema "private" "OrderSaleProjectQuery"
schema "private" "ReplaceRoundWhitelistMultipart"
schema "public" "OrderSaleProjectRoundReference"
schema "public" "OpenSaleOrder"
schema "public" "OrderSalePortfolioResults"
schema "public" "OrderSaleProject"
schema "public" "OrderSaleProjectReference"
schema "public" "OrderSaleProjectResults"
schema "public" "UnsignedSaleOrder"

### Dex :: Order Swap
schema "private" "OrderSwapQuery"
schema "private" "OrderSwapBestAvailableQuery"
schema "public" "BestAvailableSwapOrderResults"
schema "public" "CancelSwapOrder"
schema "public" "FillSwapOrder"
schema "public" "FillSwapOrders"
schema "public" "OpenSwapOrder"
schema "public" "SwapOrder"
schema "public" "SwapOrderMakerTotalFeesDeposit"
schema "public" "SwapOrderTakerTotalFees"
schema "public" "SwapOrderResults"
schema "public" "UnsignedTransaction"

### Dex :: Trading Wallet
schema "private" "TradingWalletListQuery"
schema "private" "TradingWalletQuery"
schema "public" "TradingWalletsResult"
schema "public" "TradingWallet"
schema "public" "TradingWalletResult"
schema "public" "RegisterTradingWallet"
schema "public" "TradingWalletRegisterResult"

### Dex :: Stake Vault
schema "private" "StakeVaultsQuery"
schema "private" "StakingProjectNftsQuery"
schema "private" "StakingProjectsQuery"
schema "public" "CreateStakeVault"
schema "public" "StakeVaultCreateRewardsEstimateResponse"
schema "public" "StakeVaultsResult"
schema "public" "StakingProjectNftsResult"
schema "public" "StakingProjectsResult"
schema "public" "UnsignedStakeVault"
schema "public" "UnstakeStakeVault"
schema "public" "UnsignedUnstakeStakeVault"
schema "public" "StakeVaultNftUsageReport"

### Dex :: Yield Farming Rewards
schema "private" "YieldFarmingRewardsQuery"
schema "public" "YieldFarmingRewardsClaim"
schema "public" "YieldFarmingRewardsResult"

### Dex :: Liquidity Pool
schema "private" "LiquidityPoolQuery"
schema "public" "LiquidityPool"
schema "public" "LiquidityPoolReference"
schema "public" "LiquidityPoolsResults"

### DEX :: Market Data
schema "private" "MarketAggPriceHistoryQuery"
schema "public" "MarketAggPrice"
schema "public" "MarketKline"
schema "private" "MarketMakerMetricsBinnedOrdersQuery"
schema "public" "MarketMakerMetricsBinnedOrders"

### DEX :: Options
schema "public" "CreateOption"
schema "public" "RetrieveOption"
schema "public" "ExecuteOption"

### DEX ::: Smart Vault
schema "public" "SmartVaultOpen"
schema "public" "SmartVaultDeposit"
schema "public" "SmartVaultWithdraw"
schema "public" "SmartVaultWithdrawEstimate"
schema "public" "SmartVaultWithdrawEstimateResult"
schema "public" "SmartVaultClose"
schema "public" "SmartVaultOperation"

schema "private" "SmartVaultListQuery"
schema "public" "SmartVaultListResult"

schema "private" "SmartVaultOperationListQuery"
schema "public" "SmartVaultOperationListResult"

schema "private" "SmartVaultQuery"
schema "public" "SmartVaultResult"

### Dex :: Smart Vault Strategy
schema "public" "SmartVaultStrategyListResult"
