import {
  ConnectErrorCode,
  NetworkErrorCode,
  OrderErrorCode,
  SaleOrderErrorCode,
  StakeVaultErrorCode,
  TradingWalletErrorCode,
  TransactionErrorCode,
} from '~/domain/models/public';

export {AbstractError} from '~/domain/models/public';

export type PublicErrors =
  | ConnectErrorCode
  | NetworkErrorCode
  | TransactionErrorCode
  | OrderErrorCode
  | SaleOrderErrorCode
  | StakeVaultErrorCode
  | TradingWalletErrorCode;

export class PublicError extends Error {
  constructor(readonly errorCode: PublicErrors, message: string | null = null) {
    super(message || errorCode);
  }
}

export const PublicErrorCode: {
  [key in PublicErrors]: key;
} = {
  TRANSACTION__NO_SUITABLE_COLLATERAL: 'TRANSACTION__NO_SUITABLE_COLLATERAL',
  INVALID_ORDER__INSUFFICIENT_BALANCE: 'INVALID_ORDER__INSUFFICIENT_BALANCE',
  INVALID_ORDER__TOO_EARLY_PLACE: 'INVALID_ORDER__TOO_EARLY_PLACE',
  INVALID_ORDER__TOO_LATE_PLACE: 'INVALID_ORDER__TOO_LATE_PLACE',
  INVALID_ORDER__INVALID_USER: 'INVALID_ORDER__INVALID_USER',
  INVALID_ORDER__UTXO_CONSUMED: 'INVALID_ORDER__UTXO_CONSUMED',
  INVALID_ORDER__ORDER_NOT_ACTIVE_OR_EXPIRED:
    'INVALID_ORDER__ORDER_NOT_ACTIVE_OR_EXPIRED',
  INVALID_TRADING_WALLET__INCORRECT_STAKE_KEY_HASH_FORMAT:
    'INVALID_TRADING_WALLET__INCORRECT_STAKE_KEY_HASH_FORMAT',
  INVALID_TRADING_WALLET__ALREADY_EXISTS:
    'INVALID_TRADING_WALLET__ALREADY_EXISTS',
  USER_CONNECT__INVALID_USER: 'USER_CONNECT__INVALID_USER',
  REQUEST_VALIDATION__MISSING_ROUND_ID: 'REQUEST_VALIDATION__MISSING_ROUND_ID',
  REQUEST_VALIDATION__MISSING_ORDER_ID: 'REQUEST_VALIDATION__MISSING_ORDER_ID',
  NETWORK__TIMEOUT: 'NETWORK__TIMEOUT',
  INVALID_STAKE_VAULT__NFT_COMBINATION: 'INVALID_STAKE_VAULT__NFT_COMBINATION',
  INVALID_STAKE_VAULT__VESTING_NFTS_NOT_ALLOWED:
    'INVALID_STAKE_VAULT__VESTING_NFTS_NOT_ALLOWED',
  INVALID_STAKE_VAULT__INSUFFICIENT_BALANCE:
    'INVALID_STAKE_VAULT__INSUFFICIENT_BALANCE',
  INVALID_STAKE_VAULT__WALLET_ADDRESS_MISSING_STAKE_PART:
    'INVALID_STAKE_VAULT__WALLET_ADDRESS_MISSING_STAKE_PART',
  INVALID_STAKE_VAULT__INVALID_LOCK_DURATION:
    'INVALID_STAKE_VAULT__INVALID_LOCK_DURATION',
  INVALID_STAKE_VAULT__STAKED_ASSET_TOTAL_AMOUNT_LIMIT_REACHED:
    'INVALID_STAKE_VAULT__STAKED_ASSET_TOTAL_AMOUNT_LIMIT_REACHED',
  INVALID_STAKE_VAULT__STAKED_ASSET_AMOUNT_NOT_NUMBER:
    'INVALID_STAKE_VAULT__STAKED_ASSET_AMOUNT_NOT_NUMBER',
  ORDER__BEST_AVAILABLE_ORDER_NOT_FOUND:
    'ORDER__BEST_AVAILABLE_ORDER_NOT_FOUND',
};

export enum CoreErrorCodeToPublicErrorCodeMap {
  INSUFFICIENT_BALANCE = 'INVALID_ORDER__INSUFFICIENT_BALANCE',
  TOO_EARLY_PLACE = 'INVALID_ORDER__TOO_EARLY_PLACE',
  TOO_LATE_PLACE = 'INVALID_ORDER__TOO_LATE_PLACE',
  UTXO_CONSUMED = 'INVALID_ORDER__UTXO_CONSUMED',
  NO_SUITABLE_COLLATERAL = 'TRANSACTION__NO_SUITABLE_COLLATERAL',
}

export enum ErrorCode {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  WALLET_ADDRESS_MISSING_STAKE_PART = 'WALLET_ADDRESS_MISSING_STAKE_PART',

  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  ROUND_NOT_FOUND = 'ROUND_NOT_FOUND',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',

  USER__COUNTRY_ID_NOT_FOUND = 'USER__COUNTRY_ID_NOT_FOUND',
  USER__WALLET_STAKE_KEY_HASH_NOT_FOUND = 'USER__WALLET_STAKE_KEY_HASH_NOT_FOUND',

  HTTP__USER_NOT_ATTACHED_TO_REQUEST = 'HTTP__USER_NOT_ATTACHED_TO_REQUEST',

  ORDER__USER_NOT_ATTACHED_TO_REQUEST = 'ORDER__USER_NOT_ATTACHED_TO_REQUEST',
  ORDER__FILTER_BY_WALLET_AND_OWNER = 'ORDER__FILTER_BY_WALLET_AND_OWNER',

  TRADING_WALLET__USER_NOT_ATTACHED_TO_REQUEST = 'TRADING_WALLET__USER_NOT_ATTACHED_TO_REQUEST',
  TRADING_WALLET__NOT_FOUND = 'TRADING_WALLET__NOT_FOUND',
  TRADING_WALLET__PRICE_ASSET_NOT_FOUND = 'TRADING_WALLET__PRICE_ASSET_NOT_FOUND',

  KYC__DATA_NOT_FOUND = 'KYC__DATA_NOT_FOUND',
  KYC__DOCUMENT_EXPIRED = 'KYC__DOCUMENT_EXPIRED',
  KYC__INVALID_DOCUMENT = 'KYC__INVALID_DOCUMENT',
  KYC__CONNECTION_ERROR = 'KYC__CONNECTION_ERROR',
  KYC__PROVIDER_INVALID = 'KYC__PROVIDER_INVALID',

  ASSET__INVALID_ARGUMENT = 'ASSET__INVALID_ARGUMENT',
  TEAM_MEMBER__INVALID_ARGUMENT = 'TEAM_MEMBER__INVALID_ARGUMENT',

  INVALID_TERMS__VERSION_MISMATCH = 'INVALID_TERMS__VERSION_MISMATCH',
  INVALID_ROUND__SCRIPT_ADDRESS_REQUIRED = 'INVALID_ROUND__SCRIPT_ADDRESS_REQUIRED',

  ORDER__NOT_FOUND = 'ORDER__NOT_FOUND',

  ORDER__INVALID_ROUND_STATUS = 'ORDER__INVALID_ROUND_STATUS',

  INVALID_ORDER__TRANSACTION_NOT_FOUND = 'INVALID_ORDER__TRANSACTION_NOT_FOUND',
  INVALID_ORDER__TRANSACTION_OPEN_NOT_FOUND = 'INVALID_ORDER__TRANSACTION_OPEN_NOT_FOUND',
  INVALID_ORDER__TRANSACTION_REFERENCE_NOT_FOUND = 'INVALID_ORDER__TRANSACTION_REFERENCE_NOT_FOUND',
  INVALID_ORDER__INVALID_USER = 'INVALID_ORDER__INVALID_USER',
  INVALID_ORDER__ORDER_NOT_ACTIVE_OR_EXPIRED = 'INVALID_ORDER__ORDER_NOT_ACTIVE_OR_EXPIRED',
  INVALID_ORDER__TO_OR_FROM_ASSET_AMOUNT_REQUIRED = 'INVALID_ORDER__TO_OR_FROM_ASSET_AMOUNT_REQUIRED',
  INVALID_ORDER__UTXO_CONSUMED = 'INVALID_ORDER__UTXO_CONSUMED',

  ORDER__ORDER_NOT_FOUND = 'ORDER__ORDER_NOT_FOUND',
  ORDER__BEST_AVAILABLE_ORDER_NOT_FOUND = 'ORDER__BEST_AVAILABLE_ORDER_NOT_FOUND',
  ORDER__TRANSACTION_NOT_FOUND = 'ORDER__TRANSACTION_NOT_FOUND',
  ORDER__TRANSACTION_ALREADY_EXISTS = 'ORDER__TRANSACTION_ALREADY_EXISTS',
  ORDER__TRANSACTION_OPEN_NOT_FOUND = 'ORDER__TRANSACTION_OPEN_NOT_FOUND',
  ORDER__TRANSACTION_REFERENCE_NOT_FOUND = 'ORDER__TRANSACTION_REFERENCE_NOT_FOUND',
  ORDER__TRANSACTION_FEE_DEPOSIT_AMOUNT_REQUIRED = 'ORDER__TRANSACTION_FEE_DEPOSIT_AMOUNT_REQUIRED',
  ORDER__MINT_ASSET_MISMATCH_ONE_EXPECTED = 'ORDER__MINT_ASSET_MISMATCH_ONE_EXPECTED',

  ORDER__UNEXPECTED_TRANSACTION_TYPE_FILL = 'ORDER__UNEXPECTED_TRANSACTION_TYPE_FILL',
  ORDER__UNEXPECTED_TRANSACTION_TYPE_CANCEL = 'ORDER__UNEXPECTED_TRANSACTION_TYPE_CANCEL',
  ORDER__UNEXPECTED_TRANSACTION_TYPE_CANCEL_OR_FULL_FILL = 'ORDER__UNEXPECTED_TRANSACTION_TYPE_CANCEL_OR_FULL_FILL',

  EVENT__FAILED_TO_RESOLVE_EVENT_HANDLER = 'EVENT__FAILED_TO_RESOLVE_EVENT_HANDLER',
  EVENT__EVENT_STREAM_NOT_FOUND = 'EVENT__EVENT_STREAM_NOT_FOUND',
  ON_CHAIN_EVENT__FAILED_TO_RESOLVE_EVENT_HANDLER = 'ON_CHAIN_EVENT__FAILED_TO_RESOLVE_EVENT_HANDLER',

  ORDER__EVENT_NOT_FOUND = 'ORDER__EVENT_NOT_FOUND',
  ORDER__EVENT_INCORRECT_TYPE = 'ORDER__EVENT_INCORRECT_TYPE',
  ORDER__UNEXPECTED_STATUS_CANCEL = 'ORDER__UNEXPECTED_STATUS_CANCEL',
  ORDER__TRANSACTION_OUTPUT_NOT_FOUND = 'ORDER__TRANSACTION_OUTPUT_NOT_FOUND',
  ORDER__TRANSACTION_OUTPUT_ASSETS_REQUIRED = 'ORDER__TRANSACTION_OUTPUT_ASSETS_REQUIRED',

  ORDER__UNEXPECTED_ORDER_SALES_FOR_A_GIVEN_TRANSACTION_INPUT_OR_OUTPUT = 'ORDER__UNEXPECTED_ORDER_SALES_FOR_A_GIVEN_TRANSACTION_INPUT_OR_OUTPUT',

  ORDER_SWAP__EXCLUSION_CACHE__INVALID_ORDERS_RECEIVED = 'ORDER_SWAP__EXCLUSION_CACHE__INVALID_ORDERS_RECEIVED',

  MARKET_DATA__EXTERNAL_MARKET_PRICE_DATA_NOT_FOUND = 'MARKET_DATA__EXTERNAL_MARKET_PRICE_DATA_NOT_FOUND',

  PROJECTION__CRITICAL_FAILED_TO_PROJECT = 'PROJECTION__CRITICAL_FAILED_TO_PROJECT',

  ONCHAIN_EVENT__CRITICAL_FAILED_TO_PARSE_NEW_ORDER_OUTPUT = 'ONCHAIN_EVENT__CRITICAL_FAILED_TO_PARSE_NEW_ORDER_OUTPUT',
  ONCHAIN_EVENT__CRITICAL_FAILED_TO_PARSE_PARTIAL_FILL_OUTPUT = 'ONCHAIN_EVENT__CRITICAL_FAILED_TO_PARSE_PARTIAL_FILL_OUTPUT',
  ONCHAIN_EVENT__CRITICAL_FAILED_TO_FIND_ORDER = 'ONCHAIN_EVENT__CRITICAL_FAILED_TO_FIND_ORDER',
  ONCHAIN_EVENT__CRITICAL_FAILED_TO_FIND_SMART_VAULT = 'ONCHAIN_EVENT__CRITICAL_FAILED_TO_FIND_SMART_VAULT',
  ONCHAIN_EVENT__CRITICAL_FAILED_TO_CATEGORIZE_BURN = 'ONCHAIN_EVENT__CRITICAL_FAILED_TO_CATEGORIZE_BURN',
  ONCHAIN_EVENT__BLOCK_ROLLBACK = 'ONCHAIN_EVENT__BLOCK_ROLLBACK',

  STAKE_VAULT__USER_NOT_ATTACHED_TO_REQUEST = 'STAKE_VAULT__USER_NOT_ATTACHED_TO_REQUEST',
  STAKE_VAULT__UNEXPECTED_REQUEST_BODY = 'STAKE_VAULT__UNEXPECTED_REQUEST_BODY',
  STAKE_VAULT__UNEXPECTED_TX_SERVER_RESPONSE = 'STAKE_VAULT__UNEXPECTED_TX_SERVER_RESPONSE',

  YIELD_FARMING__USER_NOT_ATTACHED_TO_REQUEST = 'YIELD_FARMING__USER_NOT_ATTACHED_TO_REQUEST',

  REQUEST_VALIDATION__MISSING_ROUND_ID = 'REQUEST_VALIDATION__MISSING_ROUND_ID',
  REQUEST_VALIDATION__MISSING_SIGNED_TRANSACTION = 'REQUEST_VALIDATION__MISSING_SIGNED_TRANSACTION',
  REQUEST_VALIDATION__MISSING_WALLET_STAKE_KEY_HASH = 'REQUEST_VALIDATION__MISSING_WALLET_STAKE_KEY_HASH',

  REQUEST_VALIDATION__MISSING_ORDER_ID = 'REQUEST_VALIDATION__MISSING_ORDER_ID',
  REQUEST_VALIDATION__MALFORMED_ASSET_PAIR_REFERENCE = 'REQUEST_VALIDATION__MALFORMED_ASSET_PAIR_REFERENCE',

  REQUEST_VALIDATION__INVALID_ISO_TIMESTAMP = 'REQUEST_VALIDATION__INVALID_ISO_TIMESTAMP',

  PROJECT_ROUND__PRICE_USD_ALREADY_DEFINED = 'PROJECT_ROUND__PRICE_USD_ALREADY_DEFINED',
  PROJECT_ROUND__PRICE_LOVELACE_ALREADY_DEFINED = 'PROJECT_ROUND__PRICE_LOVELACE_ALREADY_DEFINED',

  PROJECT_ROUND__SCRIPT_ADDRESS_MISMATCH = 'PROJECT_ROUND__SCRIPT_ADDRESS_MISMATCH',
  PROJECT_ROUND__SCRIPT_ADDRESS_ALREADY_DEFINED = 'PROJECT_ROUND__SCRIPT_ADDRESS_ALREADY_DEFINED',

  AUTHENTICATION__UNAUTHORIZED = 'AUTHENTICATION__UNAUTHORIZED',

  WHITELIST_REPLACE_FAILED = 'WHITELIST_REPLACE_FAILED',

  SMART_CONTRACT__SCRIPT_ADDRESS_NOT_FOUND = 'SMART_CONTRACT__SCRIPT_ADDRESS_NOT_FOUND',

  LIQUIDITY_POOL_NOT_FOUND = 'LIQUIDITY_POOL_NOT_FOUND',

  TRADING_PAIR_NOT_FOUND = 'TRADING_PAIR_NOT_FOUND',

  TRANSACTION_SUBMIT__UNKNOWN_ERROR = 'TRANSACTION_SUBMIT__UNKNOWN_ERROR',

  REPOSITORY_QUERY_ISSUE_DETECTED = 'REPOSITORY_QUERY_ISSUE_DETECTED',
  ORDER__INVALID_SWAP_ORDER_TYPE = 'ORDER__INVALID_SWAP_ORDER_TYPE',

  REDIS__ERROR_CACHING_PRISMA_OPERATION = 'REDIS__ERROR_CACHING_PRISMA_OPERATION',

  UNHANDLED_MARKET_ORDER_STRATEGY = 'UNHANDLED_MARKET_ORDER_STRATEGY',

  DATA_FILTER__INVALID_ARGUMENT = 'DATA_FILTER__INVALID_ARGUMENT',

  NFT_POLICY_NOT_FOUND_IN_TRANSACTION_OUTPUT = 'NFT_POLICY_NOT_FOUND_IN_TRANSACTION_OUTPUT',

  INVALID_BIN_INTERVAL_FOR_DURATION = 'INVALID_BIN_INTERVAL_FOR_DURATION',

  OPTIONS__UNEXPECTED_REQUEST_BODY = 'OPTIONS__UNEXPECTED_REQUEST_BODY',

  SMART_VAULT__FAILED_TO_CREATE = 'SMART_VAULT__FAILED_TO_CREATE',
}
